os: linux
sudo: false
language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "nightly"
  - "pypy3"
env: TOXENV=py,codecov

matrix:
  include:
    - env: TOXENV=stylecheck,docs-html
  allow_failures:
    - python: nightly
    - python: pypy3
  fast_finish: true

install:
  - pip install tox

script:
  - tox

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

branches:
  only:
    - master
    - /^.*\.x$/

notifications:
  email: false
